### ISSUE TITLE
feat : write tests for BinarySearch2dArray::BinarySearch

### ISSUE THREAD

**Issue by einbergisak** [einbergisak/Assignment3#13]
### What would you like to Propose?

Improve the coverage of the BinarySearch2dArray::BinarySearch method by implementing four new tests.

### Issue details

adding tests

**Comment by tjex** [comment]
This function already had tests or?

**Comment by einbergisak** [comment]
> This function already had tests or?

Yes, but the tests did not cover 100% of the method. I added tests that cover the rest of the branches of the method. 

We don't have to choose untested (0% coverage) methods, the only requirement is that we improve the coverage and that the chosen methods are of high cyclomatic complexity.
